x= int(input("Ingrese un numero entero"))
y = int(input("Ingrese otro numero entero"))
n=float(input("Ingrese un numero decimal"))
m = float(input("Ingrese otro numero decimal"))
print(x)
print(y)
print(n)
print(m)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(n+m)
print(n-m)
print(n*m)
print(n/m)
print(x+n)
print(y/m)
print(y%m)

